name: flatland-starterkit
dependencies:
  - python==3.12
  - pip:
      - pip
      - pyyaml
      # DEPENDENCY SWITCH:
      # TODO use versioned dependency instead of feature branch
      #      - flatland-rl[ml]
      # https://stackoverflow.com/questions/30239152/specify-extras-require-with-pip-install-e
      # does not work: #egg=flatland-rl[ml]
      - git+https://github.com/flatland-association/flatland-rl.git@policy-runner-cli-callbacks
