name: Checks

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Run single scenario
        run: |
          set -euxo pipefail
          
          docker build  -t myorga/mysolution .
          
          mkdir outputs
          chmod a+rwx outputs
          
          docker run -v ./outputs/:/tmp myorga/mysolution --data-dir /tmp --callbacks-pkg flatland.callbacks.generate_movie_callbacks --callbacks-cls GenerateMovieCallbacks
          
          find outputs

      - name: Run scenarios from metadata.csv
        run: |
          set -euxo pipefail
          
          wget "https://data.flatland.cloud/benchmarks/Flatland3/debug-environments.zip" -O debug-environments.zip -O debug-environments.zip
          mkdir -p scenarios
          unzip debug-environments.zip -d scenarios
          
          mkdir outputs-meta
          chmod a+rwx outputs-meta
          
          docker run -v ./scenarios/debug-environments/:/inputs -v ./outputs-meta:/outputs --entrypoint bash myorga/mysolution /home/conda/entrypoint_generic.sh flatland-trajectory-generate-from-metadata --metadata-csv /inputs/metadata.csv --data-dir /outputs --policy-pkg my_orga.random_policy --policy-cls RandomPolicy --obs-builder-pkg flatland.core.env_observation_builder --obs-builder-cls DummyObservationBuilder
          
          find outputs-meta
          



