name: Checks

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Download scenarios
        run: |
          wget "https://data.flatland.cloud/benchmarks/Flatland3/debug-environments.zip" -O debug-environments.zip -O debug-environments.zip
          mkdir -p scenarios
          unzip debug-environments.zip -d scenarios
      - name: Run single scenario with dla
        run: |
          set -euxo pipefail

          sudo rm -fR outputs
          mkdir outputs
          chmod a+rwx outputs

          docker pull ghcr.io/flatland-association/flatland-baselines-deadlock-avoidance-heuristic:entrypoint-refactoring
          docker run -v ./outputs/:/tmp ghcr.io/flatland-association/flatland-baselines-deadlock-avoidance-heuristic:entrypoint-refactoring flatland-trajectory-generate-from-policy --data-dir /tmp --callbacks-pkg flatland.callbacks.generate_movie_callbacks --callbacks-cls GenerateMovieCallbacks

          find outputs

      - name: Run scenarios from metadata.csv with dla
        run: |
          set -euxo pipefail

          sudo rm -fR outputs-meta
          mkdir outputs-meta
          chmod a+rwx outputs-meta

          docker pull ghcr.io/flatland-association/flatland-baselines-deadlock-avoidance-heuristic:entrypoint-refactoring
          docker run -v ./scenarios/debug-environments/:/inputs -v ./outputs-meta:/outputs ghcr.io/flatland-association/flatland-baselines-deadlock-avoidance-heuristic:entrypoint-refactoring flatland-trajectory-generate-from-metadata --metadata-csv /inputs/metadata.csv --data-dir /outputs

      - name: Build random solution
        run: |
          set -euxo pipefail
          
          docker build  -t myorga/mysolution_random .

      - name: Run single scenario with random policy
        run: |
          set -euxo pipefail
          
          sudo rm -fR outputs
          mkdir outputs
          chmod a+rwx outputs
          
          docker run -v ./outputs/:/tmp myorga/mysolution_random flatland-trajectory-generate-from-policy  --data-dir /tmp --callbacks-pkg flatland.callbacks.generate_movie_callbacks --callbacks-cls GenerateMovieCallbacks
          
          find outputs

      - name: Run scenarios from metadata.csv with random policy
        run: |
          set -euxo pipefail
          
          sudo rm -fR outputs-meta
          mkdir outputs-meta
          chmod a+rwx outputs-meta
          
          docker run -v ./scenarios/debug-environments/:/inputs -v ./outputs-meta:/outputs myorga/mysolution_random flatland-trajectory-generate-from-metadata --metadata-csv /inputs/metadata.csv --data-dir /outputs
          
          find outputs-meta
# TODO illustrate from checkpoint
#      - name: Build solution from checkpoint
#        run: |
#          set -euxo pipefail
#
#          docker build  -t myorga/mysolution_checkpoint -f Dockerfile_checkpoint .
#      - name: Run single scenario with policy from checkpoint
#        run: |
#          set -euxo pipefail
#
#          sudo rm -fR outputs
#          mkdir outputs
#          chmod a+rwx outputs
#
#          docker run -v ./outputs/:/tmp myorga/mysolution_checkpoint flatland-trajectory-generate-from-policy --data-dir /tmp --callbacks-pkg flatland.callbacks.generate_movie_callbacks --callbacks-cls GenerateMovieCallbacks
#
#          find outputs